version: "2.22.0"
services:
  db:
    image: "postgres:16.1"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5433:5432"