spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true



